name: flutter_video_trimmer
description: "A video trimmer plugin for Flutter."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  #video trimmer plugin
  flutter_native_video_trimmer:
  transparent_image:
  image:
  video_thumbnail:
  loading_animation_widget:
  video_player:
  path_provider:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

